apiVersion: 1

deleteDatasources:
  - name: Research metadata
    orgId: 1

datasources:
  - name: Research metadata
    uid: research-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
    editable: false
